export const CONFIG = {
  PLAYER: {
    height: 1.7,
    crouchHeight: 1.15,
    radius: 0.42,
    walkSpeed: 5.4,
    sprintSpeed: 8.6,
    crouchSpeed: 2.7,
    adsSpeedMult: 0.55,
    accelGround: 60,
    accelAir: 12,
    friction: 10,
    jumpVel: 6.8,
    gravity: 21,
    maxHealth: 100,
    regenDelay: 4.2,
    regenRate: 38
  },
  ENEMY: {
    health: 100,
    headshotMult: 2.4,
    walkSpeed: 3.0,
    sprintSpeed: 5.2,
    fireRange: 60,
    burstSize: 4,
    burstInterval: 0.11,
    burstCooldown: 1.35,
    baseAccuracy: 0.28,
    accuracyPerWave: 0.02,
    maxAccuracy: 0.62,
    dmgPerHit: [7, 13],
    flinchTime: 0.22
  },
  WAVE: {
    baseCount: 4,
    perWave: 2,
    maxAlive: 9,
    intermission: 6,
    healOnClear: 40,
    reserveRefillFrac: 0.5
  },
  WEAPONS: {
    ar: {
      name: 'M4 VANDAL',
      auto: true,
      rpm: 800,
      damage: 26,
      pellets: 1,
      magSize: 30,
      reserveMax: 150,
      reloadTime: 2.1,
      spreadHip: 1.6,
      spreadAds: 0.18,
      bloomPerShot: 0.45,
      recoilKick: 0.9,
      recoilRecover: 9,
      adsFov: 58,
      range: 220,
      tracerEvery: 1
    },
    smg: {
      name: 'HORNET SMG',
      auto: true,
      rpm: 950,
      damage: 19,
      pellets: 1,
      magSize: 32,
      reserveMax: 192,
      reloadTime: 1.75,
      spreadHip: 2.4,
      spreadAds: 0.55,
      bloomPerShot: 0.4,
      recoilKick: 0.65,
      recoilRecover: 11,
      adsFov: 60,
      range: 120,
      tracerEvery: 1
    },
    shotgun: {
      name: 'BREACHER 12G',
      auto: false,
      rpm: 78,
      damage: 14,
      pellets: 8,
      magSize: 6,
      reserveMax: 36,
      reloadTime: 2.8,
      spreadHip: 5.5,
      spreadAds: 3.8,
      bloomPerShot: 0.6,
      recoilKick: 2.4,
      recoilRecover: 7,
      adsFov: 62,
      range: 45,
      tracerEvery: 3
    },
    sniper: {
      name: 'LOCUS .338',
      auto: false,
      rpm: 52,
      damage: 105,
      pellets: 1,
      magSize: 5,
      reserveMax: 30,
      reloadTime: 3.1,
      spreadHip: 6.0,
      spreadAds: 0.01,
      bloomPerShot: 0,
      recoilKick: 3.2,
      recoilRecover: 6,
      adsFov: 22,
      scope: true,
      range: 400,
      tracerEvery: 1
    }
  },
  SCORE: {
    kill: 100,
    headshotBonus: 50,
    streakStep: 25,
    streakCap: 5
  }
};
